<?php
/**
 *
 * Templates: Child Pages
 *
 * @author Robin Sallis
 *
 * @credits bitpoet: some code adapted from his 'Template Access by Parents' module
 * @credits hani: this module requires his 'Template ASM Select' module
 *
 * ProcessWire 2.x
 * Copyright (C) 2014 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://processwire.com
 *
 */

class TemplatesChildPages extends WireData implements Module {

	/**
	 * Module information
	 *
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Templates: Child Pages',
			'version' => '2',
			'author' => 'Robin Sallis',
			'summary' => 'For any page, allows the restricting of templates that may be used for child pages.',
			'singular' => true,
			'autoload' => "template=admin",
			'icon' => 'cubes',
			'requires' => 'FieldtypeTemplates', // 'Template ASM Select' module
		);
	}

	/**
	 * On install, add the field used for storing allowed templates
	 *
	 * @access public
	 *
	 */
	public function ___install() {
		$fields = wire('fields');
		if(!$fields->get('templates_child_pages')) {
			$f = new Field();
			$f->type = $this->modules->get('FieldtypeTemplates');
			$f->name = 'templates_child_pages';
			$f->tags = 'TemplatesChildPages';
			$f->label = 'Template restrictions for children';
			$f->description = 'If empty no additional restrictions on templates are applied.';
			$f->addFlag(32); // Field is access controlled (superuser only)
			$f->collapsed = Inputfield::collapsedHidden; // Field is hidden
			$f->save();
		}
	}

	/**
	 * Initialise
	 *
	 * @access public
	 *
	 */
	public function init() {
		$this->addHookAfter('ProcessPageEdit::buildFormChildren', $this, 'appendFieldToForm');
		$this->addHookAfter('Pages::saveReady', $this, 'saveTemplatesField');
		$this->addHookAfter('ProcessPageAdd::getAllowedTemplates', $this, 'filterAllowedTemplates');
	}

	/**
	 * Append allowed templates field to Children tab form
	 *
	 * @access public
	 *
	 */
	public function appendFieldToForm($event) {
		if(!wire('user')->isSuperuser()) return;
		$page = $event->object->getPage();
		if($page->template->hasField('templates_child_pages')) {
			$field = wire('fields')->get('templates_child_pages');
			$if = $field->getInputfield($page);
			$form = $event->return;
			// Get value of 'templates_child_pages' field
			$allowed_templates = $page->templates_child_pages;
			// Create and append inputfield
			$f = wire('modules')->FieldtypeTemplates->getInputfield($page, $field);
			$f->attr('name', 'allowed_templates');
			$f->label = $if->label;
			$f->description = $if->description;
			$f->attr('value', $allowed_templates);
			$form->append($f);
		}
	}

	/**
	 * Save allowed templates
	 *
	 * @access public
	 *
	 */
	public function saveTemplatesField($event) {
		if(!wire('user')->isSuperuser()) return;
		$page = $event->arguments('page');
		if($page->template->hasField('templates_child_pages')) {
			$allowed_templates = wire('input')->post->allowed_templates;
			// Set value of 'templates_child_pages' field
			if(is_array($allowed_templates)) {
				$allowed_templates_int = array();
				foreach ($allowed_templates as $template_id) {
					$allowed_templates_int[] = (int)$template_id;
				}
				$page->templates_child_pages = $allowed_templates_int;
			} else {
				$page->templates_child_pages = '';
			}
		}
	}

	/**
	 * Filter allowed templates
	 *
	 * @access public
	 *
	 */
	public function filterAllowedTemplates($event) {
		// Get parent page
		$parent = $event->arguments(0);
		if(! $parent) {
			$parent = wire('pages')->get((int)$this->input->get->parent_id);
		}
		if(! $parent) {
			$parent = wire('pages')->get((int)$this->input->post->parent_id);
		}
		if($parent instanceof NullPage) return;
		// Filter templates
		$templates = $event->return;
		$allowed_templates = $parent->templates_child_pages;
		if($allowed_templates) {
			$out = array();
			foreach($templates as $template) {
				if(in_array($template->id, $allowed_templates)) {
					$out[$template->id] = $template;
				}
			}
			$event->return = $out;
		}
	}

	/**
	 * On uninstall, delete the field used for storing allowed templates
	 *
	 * @access public
	 *
	 */
	public function ___uninstall() {
		$fields = wire('fields');
		$f = $fields->get('templates_child_pages');
		if($f) {
			$f_groups = $f->getFieldgroups();
			foreach ($f_groups as $f_group) {
				$f_group->remove($f);
				$f_group->save();
			}
			$fields->delete($f);
		}
	}

}
